apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: webservice
  namespace: namespace1
  labels:
    serving.knative.dev/visibility: cluster-local
    folder: webservice
spec:
  template:
    spec:
      imagepullsecrets:
        - name: regcred
      containers:
        - image: namespace1-webservice